[Snyk] Upgrade semantic-ui-react from 1.0.0 to 1.3.1
newrelic/nr1-integrations-manager pull request #72
Opened 2021-02-03 23:39 UTC by timglaser

<h3>Snyk has created this PR to upgrade semantic-ui-react from 1.0.0 to 1.3.1.</h3>

![merge advice](https://app.snyk.io/badges/merge-advice/?package_manager=npm&package_name=semantic-ui-react&from_version=1.0.0&to_version=1.3.1&pr_id=31a1af2a-9480-4de9-a873-01afdbf30def&visibility=true&has_feature_flag=false)
:information_source: Keep your dependencies up-to-date. This makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect your project.
<hr/>

- The recommended version is **6 versions** ahead of your current version.
- The recommended version was released **4 months ago**, on 2020-09-29.

<details>
<summary><b>Release notes</b></summary>
<br/>
  <details>
    <summary>Package name: <b>semantic-ui-react</b></summary>
    <ul>
      <li>
        <b>1.3.1</b> - <a href="https://snyk.io/redirect/github/Semantic-Org/Semantic-UI-React/releases/tag/v1.3.1">2020-09-29</a></br><h4><g-emoji class="g-emoji" alias="bug" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f41b.png">🐛</g-emoji> Bug Fix</h4>
<ul>
<li><a href="https://snyk.io/redirect/github/Semantic-Org/Semantic-UI-React/pull/4079" data-hovercard-type="pull_request" data-hovercard-url="/Semantic-Org/Semantic-UI-React/pull/4079/hovercard">#4079</a> fix(TextArea): update onChange type (<a href="https://snyk.io/redirect/github/foooomio">@ foooomio</a>)</li>
</ul>
<h4><g-emoji class="g-emoji" alias="house" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f3e0.png">🏠</g-emoji> Internal</h4>
<ul>
<li><a href="https://snyk.io/redirect/github/Semantic-Org/Semantic-UI-React/pull/4072" data-hovercard-type="pull_request" data-hovercard-url="/Semantic-Org/Semantic-UI-React/pull/4072/hovercard">#4072</a> chore: use lodash-es to improve bundle size (<a href="https://snyk.io/redirect/github/layershifter">@ layershifter</a>)</li>
<li><a href="https://snyk.io/redirect/github/Semantic-Org/Semantic-UI-React/pull/4073" data-hovercard-type="pull_request" data-hovercard-url="/Semantic-Org/Semantic-UI-React/pull/4073/hovercard">#4073</a> chore: remove usages of <code>lodash/fp</code> in customPropTypes (<a href="https://snyk.io/redirect/github/layershifter">@ layershifter</a>)</li>
<li><a href="https://snyk.io/redirect/github/Semantic-Org/Semantic-UI-React/pull/4068" data-hovercard-type="pull_request" data-hovercard-url="/Semantic-Org/Semantic-UI-React/pull/4068/hovercard">#4068</a> chore: bump update a package with <code>Ref</code> component (<a href="https://snyk.io/redirect/github/layershifter">@ layershifter</a>)</li>
</ul>
<h4>Committers: 2</h4>
<ul>
<li>Oleksandr Fediashov (<a href="https://snyk.io/redirect/github/layershifter">@ layershifter</a>)</li>
<li>foooomio (<a href="https://snyk.io/redirect/github/foooomio">@ foooomio</a>)</li>
</ul>
      </li>
      <li>
        <b>1.3.0</b> - <a href="https://snyk.io/redirect/github/Semantic-Org/Semantic-UI-React/releases/tag/v1.3.0">2020-09-22</a></br><h4><g-emoji class="g-emoji" alias="rocket" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f680.png">🚀</g-emoji> New Feature</h4>
<ul>
<li><a href="https://snyk.io/redirect/github/Semantic-Org/Semantic-UI-React/pull/4029" data-hovercard-type="pull_request" data-hovercard-url="/Semantic-Org/Semantic-UI-React/pull/4029/hovercard">#4029</a> feat: introduce <code>children</code> function to shorthands (<a href="https://snyk.io/redirect/github/layershifter">@ layershifter</a>)</li>
</ul>
<h4><g-emoji class="g-emoji" alias="bug" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f41b.png">🐛</g-emoji> Bug Fix</h4>
<ul>
<li><a href="https://snyk.io/redirect/github/Semantic-Org/Semantic-UI-React/pull/4060" data-hovercard-type="pull_request" data-hovercard-url="/Semantic-Org/Semantic-UI-React/pull/4060/hovercard">#4060</a> fix(Transition): schedule changes only on <code>status</code> change (<a href="https://snyk.io/redirect/github/layershifter">@ layershifter</a>)</li>
<li><a href="https://snyk.io/redirect/github/Semantic-Org/Semantic-UI-React/pull/4047" data-hovercard-type="pull_request" data-hovercard-url="/Semantic-Org/Semantic-UI-React/pull/4047/hovercard">#4047</a> fix(Dropdown): handle <code>text</code> as a content in <code>renderLabel</code> (<a href="https://snyk.io/redirect/github/layershifter">@ layershifter</a>)</li>
</ul>
<h4>Committers: 1</h4>
<ul>
<li>Oleksandr Fediashov (<a href="https://snyk.io/redirect/github/layershifter">@ layershifter</a>)</li>
</ul>
      </li>
      <li>
        <b>1.2.1</b> - <a href="https://snyk.io/redirect/github/Semantic-Org/Semantic-UI-React/releases/tag/v1.2.1">2020-08-19</a></br><h4><g-emoji class="g-emoji" alias="bug" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f41b.png">🐛</g-emoji> Bug Fix</h4>
<ul>
<li><a href="https://snyk.io/redirect/github/Semantic-Org/Semantic-UI-React/pull/4037" data-hovercard-type="pull_request" data-hovercard-url="/Semantic-Org/Semantic-UI-React/pull/4037/hovercard">#4037</a> fix(Pagination): set a default activePage in Pagination's state (<a href="https://snyk.io/redirect/github/gcalica">@ gcalica</a>)</li>
<li><a href="https://snyk.io/redirect/github/Semantic-Org/Semantic-UI-React/pull/4041" data-hovercard-type="pull_request" data-hovercard-url="/Semantic-Org/Semantic-UI-React/pull/4041/hovercard">#4041</a> fix(Dropdown): fix handling of "Space" key  (<a href="https://snyk.io/redirect/github/layershifter">@ layershifter</a>)</li>
<li><a href="https://snyk.io/redirect/github/Semantic-Org/Semantic-UI-React/pull/4043" data-hovercard-type="pull_request" data-hovercard-url="/Semantic-Org/Semantic-UI-React/pull/4043/hovercard">#4043</a> fix(FormField): fix aria-invalid on error false (<a href="https://snyk.io/redirect/github/aoelen">@ aoelen</a>)</li>
</ul>
<h4><g-emoji class="g-emoji" alias="memo" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4dd.png">📝</g-emoji> Documentation</h4>
<ul>
<li><a href="https://snyk.io/redirect/github/Semantic-Org/Semantic-UI-React/pull/4040" data-hovercard-type="pull_request" data-hovercard-url="/Semantic-Org/Semantic-UI-React/pull/4040/hovercard">#4040</a> docs(Placeholder): fix description of the component (<a href="https://snyk.io/redirect/github/eugenelim">@ eugenelim</a>)</li>
<li><a href="https://snyk.io/redirect/github/Semantic-Org/Semantic-UI-React/pull/4039" data-hovercard-type="pull_request" data-hovercard-url="/Semantic-Org/Semantic-UI-React/pull/4039/hovercard">#4039</a> docs(Ref): restore docs for a component (<a href="https://snyk.io/redirect/github/layershifter">@ layershifter</a>)</li>
</ul>
<h4><g-emoji class="g-emoji" alias="house" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f3e0.png">🏠</g-emoji> Internal</h4>
<ul>
<li><a href="https://snyk.io/redirect/github/Semantic-Org/Semantic-UI-React/pull/4023" data-hovercard-type="pull_request" data-hovercard-url="/Semantic-Org/Semantic-UI-React/pull/4023/hovercard">#4023</a> chore: update Ref dependency to latest version (<a href="https://snyk.io/redirect/github/jluxenberg">@ jluxenberg</a>)</li>
</ul>
<h4>Committers: 5</h4>
<ul>
<li>Gian Paolo Calica (<a href="https://snyk.io/redirect/github/gcalica">@ gcalica</a>)</li>
<li>Jared Luxenberg (<a href="https://snyk.io/redirect/github/jluxenberg">@ jluxenberg</a>)</li>
<li>Oleksandr Fediashov (<a href="https://snyk.io/redirect/github/layershifter">@ layershifter</a>)</li>
<li><a href="https://snyk.io/redirect/github/eugenelim">@ eugenelim</a></li>
<li><a href="https://snyk.io/redirect/github/aoelen">@ aoelen</a></li>
</ul>
      </li>
      <li>
        <b>1.2.0</b> - <a href="https://snyk.io/redirect/github/Semantic-Org/Semantic-UI-React/releases/tag/v1.2.0">2020-08-12</a></br><h4><g-emoji class="g-emoji" alias="rocket" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f680.png">🚀</g-emoji> New Feature</h4>
<ul>
<li><a href="https://sny [...]

2021-02-03 23:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/nr1-integrations-manager?pullRequest=72) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/nr1-integrations-manager?pullRequest=72) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/nr1-integrations-manager?pullRequest=72) it.</sub>

2021-02-23 22:49 UTC, jpvajda approved these changes

2021-03-11 01:54 UTC, jpvajda requested changes
failing checks...

2021-03-26 21:04 UTC, LizBaker approved these changes

2021-03-26 21:05 UTC, merged